services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=readygsm'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=readygsm'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
