spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENTS_ID}
            client-secret: ${CLIENTS_PASSWORD}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/token"
        provider:
          google:
            user-name-attribute: sub
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
