services:
  app:
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    restart: always
    networks:
      - readygsm-net

networks:
  readygsm-net:
    driver: bridge